# Generated by Django 2.2.4 on 2019-12-29 12:39

import Medical_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(verbose_name=Medical_system.models.Patient)),
                ('doctor', models.IntegerField(verbose_name=Medical_system.models.Patient)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(verbose_name=Medical_system.models.Patient)),
                ('video', models.IntegerField(verbose_name=Medical_system.models.Video)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(verbose_name=Medical_system.models.Patient)),
                ('video', models.IntegerField(verbose_name=Medical_system.models.Video)),
                ('time', models.DateTimeField(auto_now=True)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=20)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('person_info', models.CharField(max_length=100)),
                ('hospital_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=20)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(verbose_name=Medical_system.models.Patient)),
                ('video', models.IntegerField(verbose_name=Medical_system.models.Video)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='files')),
                ('time', models.DateTimeField(auto_now=True)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
